version: "3.9"

services:
 cleanalyze:
 build:
 context: .
 dockerfile: dockerfile
 environment:
 - PORT=8080
 restart: unless-stopped
 networks:
 - proxy_default
 labels:
 - "traefik.enable=true"
 - "traefik.http.routers.cleanalyze.rule=Host(`cleanalyze.desenvolvimentobbz.cloud`)"
 - "traefik.http.routers.cleanalyze.entrypoints=websecure"
 - "traefik.http.routers.cleanalyze.tls.certresolver=le"
 - "traefik.http.services.cleanalyze.loadbalancer.server.port=8080"

networks:
 proxy_default:
 external: true
