version: "3.9"

services:
  cleanalyze:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/var/www/html/.env:ro
      - ./auth/data:/var/www/html/auth/data
      - ./output:/var/www/html/output
      - ./uploads:/var/www/html/uploads
